import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: "#CCCC",
    paddingTop: Platform.OS === "ios" ? 64 : 50,
  },
  menu: {
    width: "100%",
    height: 230,
    marginTop: -50,
    backgroundColor: "#141414",
    alignItems: "center",
  },
  card: {
    width: 180,
    height: 225,
    margin: 5,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#212121",
    borderWidth: 1.5,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    color: "#ffff",
  },
  imgCard: {
    width: 80,
    height: 80,
    marginTop: 5,
  },
  buttonDeletSkill: {
    backgroundColor: "red",
    width: 80,
    height: 30,
    margin: 8,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  divLevel: {
    flexDirection: "row",
    alignItems: "center",
  },
  buttonDecrease: {
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    color: "white",
    backgroundColor: "#D6450D",
  },
  buttonIncrease: {
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    color: "white",
    backgroundColor: "#39D121",
  },
  titleLevel: {
    fontSize: 16,
    marginHorizontal: 10,
    color: "#17BCD1",
  },
});
